PROJ_NAME = Example_GPIO_EXTI
VPATH = Src Inc
LFLAGS  = -T./SW4STM32/STM32F429I-Discovery/STM32F429ZITx_FLASH.ld
SRCS     += stm32f4xx_it.c
SRCS     += system_stm32f4xx.c
SRCS     += stm32f4xx_hal.c
SRCS     += stm32f4xx_hal_rcc.c
SRCS     += stm32f4xx_hal_cortex.c
SRCS     += stm32f4xx_hal_gpio.c
SRCS     += stm32f4xx_hal_pwr_ex.c
include ../../../../Makefile.Example

#vpath %.h $(INC_DIRS)
#SRCS     += stm32f4xx_it.c
#SRCS     += system_stm32f4xx.c

